name: Smart Tests Demo

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SMART_TESTS_TOKEN: ${{ secrets.SMART_TESTS_TOKEN }}
  SMART_TESTS_REPORT_ERROR: 1

jobs:
  example-jest-unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: |
          npm run test:unit
